/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserPrivateInfoService } from "../userPrivateInfo.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserPrivateInfoCreateInput } from "./UserPrivateInfoCreateInput";
import { UserPrivateInfo } from "./UserPrivateInfo";
import { UserPrivateInfoFindManyArgs } from "./UserPrivateInfoFindManyArgs";
import { UserPrivateInfoWhereUniqueInput } from "./UserPrivateInfoWhereUniqueInput";
import { UserPrivateInfoUpdateInput } from "./UserPrivateInfoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserPrivateInfoControllerBase {
  constructor(
    protected readonly service: UserPrivateInfoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserPrivateInfo })
  @nestAccessControl.UseRoles({
    resource: "UserPrivateInfo",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserPrivateInfoCreateInput,
  })
  async createUserPrivateInfo(
    @common.Body() data: UserPrivateInfoCreateInput
  ): Promise<UserPrivateInfo> {
    return await this.service.createUserPrivateInfo({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        birthDate: true,
        country: true,
        city: true,
        cc: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserPrivateInfo] })
  @ApiNestedQuery(UserPrivateInfoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserPrivateInfo",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userPrivateInfos(
    @common.Req() request: Request
  ): Promise<UserPrivateInfo[]> {
    const args = plainToClass(UserPrivateInfoFindManyArgs, request.query);
    return this.service.userPrivateInfos({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        birthDate: true,
        country: true,
        city: true,
        cc: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserPrivateInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserPrivateInfo",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userPrivateInfo(
    @common.Param() params: UserPrivateInfoWhereUniqueInput
  ): Promise<UserPrivateInfo | null> {
    const result = await this.service.userPrivateInfo({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        birthDate: true,
        country: true,
        city: true,
        cc: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserPrivateInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserPrivateInfo",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserPrivateInfoUpdateInput,
  })
  async updateUserPrivateInfo(
    @common.Param() params: UserPrivateInfoWhereUniqueInput,
    @common.Body() data: UserPrivateInfoUpdateInput
  ): Promise<UserPrivateInfo | null> {
    try {
      return await this.service.updateUserPrivateInfo({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          birthDate: true,
          country: true,
          city: true,
          cc: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserPrivateInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserPrivateInfo",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserPrivateInfo(
    @common.Param() params: UserPrivateInfoWhereUniqueInput
  ): Promise<UserPrivateInfo | null> {
    try {
      return await this.service.deleteUserPrivateInfo({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          birthDate: true,
          country: true,
          city: true,
          cc: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
