/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  ValidateNested,
  IsOptional,
} from "class-validator";
import { GuildsPrivateInfoCreateNestedManyWithoutGuildsInput } from "./GuildsPrivateInfoCreateNestedManyWithoutGuildsInput";
import { Type } from "class-transformer";
import { GuildsMembersCreateNestedManyWithoutGuildsInput } from "./GuildsMembersCreateNestedManyWithoutGuildsInput";
import { GuildsJoinInvitationsCreateNestedManyWithoutGuildsInput } from "./GuildsJoinInvitationsCreateNestedManyWithoutGuildsInput";
import { GuildsCoinsCreateNestedManyWithoutGuildsInput } from "./GuildsCoinsCreateNestedManyWithoutGuildsInput";
import { MissionsWhereUniqueInput } from "../../missions/base/MissionsWhereUniqueInput";

@InputType()
class GuildCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  title!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  slug!: string;

  @ApiProperty({
    required: false,
    type: () => GuildsPrivateInfoCreateNestedManyWithoutGuildsInput,
  })
  @ValidateNested()
  @Type(() => GuildsPrivateInfoCreateNestedManyWithoutGuildsInput)
  @IsOptional()
  @Field(() => GuildsPrivateInfoCreateNestedManyWithoutGuildsInput, {
    nullable: true,
  })
  guildsPrivateInfos?: GuildsPrivateInfoCreateNestedManyWithoutGuildsInput;

  @ApiProperty({
    required: false,
    type: () => GuildsMembersCreateNestedManyWithoutGuildsInput,
  })
  @ValidateNested()
  @Type(() => GuildsMembersCreateNestedManyWithoutGuildsInput)
  @IsOptional()
  @Field(() => GuildsMembersCreateNestedManyWithoutGuildsInput, {
    nullable: true,
  })
  guildsMembersItems?: GuildsMembersCreateNestedManyWithoutGuildsInput;

  @ApiProperty({
    required: false,
    type: () => GuildsJoinInvitationsCreateNestedManyWithoutGuildsInput,
  })
  @ValidateNested()
  @Type(() => GuildsJoinInvitationsCreateNestedManyWithoutGuildsInput)
  @IsOptional()
  @Field(() => GuildsJoinInvitationsCreateNestedManyWithoutGuildsInput, {
    nullable: true,
  })
  guildsJoinInvitationsItems?: GuildsJoinInvitationsCreateNestedManyWithoutGuildsInput;

  @ApiProperty({
    required: false,
    type: () => GuildsCoinsCreateNestedManyWithoutGuildsInput,
  })
  @ValidateNested()
  @Type(() => GuildsCoinsCreateNestedManyWithoutGuildsInput)
  @IsOptional()
  @Field(() => GuildsCoinsCreateNestedManyWithoutGuildsInput, {
    nullable: true,
  })
  guildsCoinsItems?: GuildsCoinsCreateNestedManyWithoutGuildsInput;

  @ApiProperty({
    required: false,
    type: () => MissionsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MissionsWhereUniqueInput)
  @IsOptional()
  @Field(() => MissionsWhereUniqueInput, {
    nullable: true,
  })
  missionsItems?: MissionsWhereUniqueInput | null;
}

export { GuildCreateInput as GuildCreateInput };
