/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { GuildsPrivateInfoListRelationFilter } from "../../guildsPrivateInfo/base/GuildsPrivateInfoListRelationFilter";
import { GuildsMembersListRelationFilter } from "../../guildsMembers/base/GuildsMembersListRelationFilter";
import { GuildsJoinInvitationsListRelationFilter } from "../../guildsJoinInvitations/base/GuildsJoinInvitationsListRelationFilter";
import { GuildsCoinsListRelationFilter } from "../../guildsCoins/base/GuildsCoinsListRelationFilter";
import { MissionsWhereUniqueInput } from "../../missions/base/MissionsWhereUniqueInput";

@InputType()
class GuildWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  title?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  slug?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => GuildsPrivateInfoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GuildsPrivateInfoListRelationFilter)
  @IsOptional()
  @Field(() => GuildsPrivateInfoListRelationFilter, {
    nullable: true,
  })
  guildsPrivateInfos?: GuildsPrivateInfoListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => GuildsMembersListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GuildsMembersListRelationFilter)
  @IsOptional()
  @Field(() => GuildsMembersListRelationFilter, {
    nullable: true,
  })
  guildsMembersItems?: GuildsMembersListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => GuildsJoinInvitationsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GuildsJoinInvitationsListRelationFilter)
  @IsOptional()
  @Field(() => GuildsJoinInvitationsListRelationFilter, {
    nullable: true,
  })
  guildsJoinInvitationsItems?: GuildsJoinInvitationsListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => GuildsCoinsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GuildsCoinsListRelationFilter)
  @IsOptional()
  @Field(() => GuildsCoinsListRelationFilter, {
    nullable: true,
  })
  guildsCoinsItems?: GuildsCoinsListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => MissionsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MissionsWhereUniqueInput)
  @IsOptional()
  @Field(() => MissionsWhereUniqueInput, {
    nullable: true,
  })
  missionsItems?: MissionsWhereUniqueInput;
}

export { GuildWhereInput as GuildWhereInput };
