/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  MaxLength,
  ValidateNested,
  IsOptional,
} from "class-validator";
import { Type } from "class-transformer";
import { GuildsPrivateInfo } from "../../guildsPrivateInfo/base/GuildsPrivateInfo";
import { GuildsMembers } from "../../guildsMembers/base/GuildsMembers";
import { GuildsJoinInvitations } from "../../guildsJoinInvitations/base/GuildsJoinInvitations";
import { GuildsCoins } from "../../guildsCoins/base/GuildsCoins";
import { Missions } from "../../missions/base/Missions";

@ObjectType()
class Guild {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  title!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  slug!: string;

  @ApiProperty({
    required: false,
    type: () => [GuildsPrivateInfo],
  })
  @ValidateNested()
  @Type(() => GuildsPrivateInfo)
  @IsOptional()
  guildsPrivateInfos?: Array<GuildsPrivateInfo>;

  @ApiProperty({
    required: false,
    type: () => [GuildsMembers],
  })
  @ValidateNested()
  @Type(() => GuildsMembers)
  @IsOptional()
  guildsMembersItems?: Array<GuildsMembers>;

  @ApiProperty({
    required: false,
    type: () => [GuildsJoinInvitations],
  })
  @ValidateNested()
  @Type(() => GuildsJoinInvitations)
  @IsOptional()
  guildsJoinInvitationsItems?: Array<GuildsJoinInvitations>;

  @ApiProperty({
    required: false,
    type: () => [GuildsCoins],
  })
  @ValidateNested()
  @Type(() => GuildsCoins)
  @IsOptional()
  guildsCoinsItems?: Array<GuildsCoins>;

  @ApiProperty({
    required: false,
    type: () => Missions,
  })
  @ValidateNested()
  @Type(() => Missions)
  @IsOptional()
  missionsItems?: Missions | null;
}

export { Guild as Guild };
