/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserRankingService } from "../userRanking.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserRankingCreateInput } from "./UserRankingCreateInput";
import { UserRanking } from "./UserRanking";
import { UserRankingFindManyArgs } from "./UserRankingFindManyArgs";
import { UserRankingWhereUniqueInput } from "./UserRankingWhereUniqueInput";
import { UserRankingUpdateInput } from "./UserRankingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserRankingControllerBase {
  constructor(
    protected readonly service: UserRankingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserRanking })
  @nestAccessControl.UseRoles({
    resource: "UserRanking",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserRankingCreateInput,
  })
  async createUserRanking(
    @common.Body() data: UserRankingCreateInput
  ): Promise<UserRanking> {
    return await this.service.createUserRanking({
      data: {
        ...data,

        user_id: data.user_id
          ? {
              connect: data.user_id,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        score: true,
        date: true,
        rank: true,

        user_id: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserRanking] })
  @ApiNestedQuery(UserRankingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserRanking",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userRankings(@common.Req() request: Request): Promise<UserRanking[]> {
    const args = plainToClass(UserRankingFindManyArgs, request.query);
    return this.service.userRankings({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        score: true,
        date: true,
        rank: true,

        user_id: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserRanking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserRanking",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userRanking(
    @common.Param() params: UserRankingWhereUniqueInput
  ): Promise<UserRanking | null> {
    const result = await this.service.userRanking({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        score: true,
        date: true,
        rank: true,

        user_id: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserRanking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserRanking",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserRankingUpdateInput,
  })
  async updateUserRanking(
    @common.Param() params: UserRankingWhereUniqueInput,
    @common.Body() data: UserRankingUpdateInput
  ): Promise<UserRanking | null> {
    try {
      return await this.service.updateUserRanking({
        where: params,
        data: {
          ...data,

          user_id: data.user_id
            ? {
                connect: data.user_id,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          score: true,
          date: true,
          rank: true,

          user_id: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserRanking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserRanking",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserRanking(
    @common.Param() params: UserRankingWhereUniqueInput
  ): Promise<UserRanking | null> {
    try {
      return await this.service.deleteUserRanking({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          score: true,
          date: true,
          rank: true,

          user_id: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
