/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserHonorGloryService } from "../userHonorGlory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserHonorGloryCreateInput } from "./UserHonorGloryCreateInput";
import { UserHonorGlory } from "./UserHonorGlory";
import { UserHonorGloryFindManyArgs } from "./UserHonorGloryFindManyArgs";
import { UserHonorGloryWhereUniqueInput } from "./UserHonorGloryWhereUniqueInput";
import { UserHonorGloryUpdateInput } from "./UserHonorGloryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserHonorGloryControllerBase {
  constructor(
    protected readonly service: UserHonorGloryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserHonorGlory })
  @nestAccessControl.UseRoles({
    resource: "UserHonorGlory",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserHonorGloryCreateInput,
  })
  async createUserHonorGlory(
    @common.Body() data: UserHonorGloryCreateInput
  ): Promise<UserHonorGlory> {
    return await this.service.createUserHonorGlory({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        honor: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserHonorGlory] })
  @ApiNestedQuery(UserHonorGloryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserHonorGlory",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userHonorGlories(
    @common.Req() request: Request
  ): Promise<UserHonorGlory[]> {
    const args = plainToClass(UserHonorGloryFindManyArgs, request.query);
    return this.service.userHonorGlories({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        honor: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserHonorGlory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserHonorGlory",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userHonorGlory(
    @common.Param() params: UserHonorGloryWhereUniqueInput
  ): Promise<UserHonorGlory | null> {
    const result = await this.service.userHonorGlory({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        honor: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserHonorGlory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserHonorGlory",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserHonorGloryUpdateInput,
  })
  async updateUserHonorGlory(
    @common.Param() params: UserHonorGloryWhereUniqueInput,
    @common.Body() data: UserHonorGloryUpdateInput
  ): Promise<UserHonorGlory | null> {
    try {
      return await this.service.updateUserHonorGlory({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          honor: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserHonorGlory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserHonorGlory",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserHonorGlory(
    @common.Param() params: UserHonorGloryWhereUniqueInput
  ): Promise<UserHonorGlory | null> {
    try {
      return await this.service.deleteUserHonorGlory({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          honor: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
