/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, UserHonorGlory as PrismaUserHonorGlory } from "@prisma/client";

export class UserHonorGloryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.UserHonorGloryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.userHonorGlory.count(args);
  }

  async userHonorGlories(
    args: Prisma.UserHonorGloryFindManyArgs
  ): Promise<PrismaUserHonorGlory[]> {
    return this.prisma.userHonorGlory.findMany(args);
  }
  async userHonorGlory(
    args: Prisma.UserHonorGloryFindUniqueArgs
  ): Promise<PrismaUserHonorGlory | null> {
    return this.prisma.userHonorGlory.findUnique(args);
  }
  async createUserHonorGlory(
    args: Prisma.UserHonorGloryCreateArgs
  ): Promise<PrismaUserHonorGlory> {
    return this.prisma.userHonorGlory.create(args);
  }
  async updateUserHonorGlory(
    args: Prisma.UserHonorGloryUpdateArgs
  ): Promise<PrismaUserHonorGlory> {
    return this.prisma.userHonorGlory.update(args);
  }
  async deleteUserHonorGlory(
    args: Prisma.UserHonorGloryDeleteArgs
  ): Promise<PrismaUserHonorGlory> {
    return this.prisma.userHonorGlory.delete(args);
  }
}
