/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  UserPortugueseGoldenCoin as PrismaUserPortugueseGoldenCoin,
} from "@prisma/client";

export class UserPortugueseGoldenCoinServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.UserPortugueseGoldenCoinCountArgs, "select">
  ): Promise<number> {
    return this.prisma.userPortugueseGoldenCoin.count(args);
  }

  async userPortugueseGoldenCoins(
    args: Prisma.UserPortugueseGoldenCoinFindManyArgs
  ): Promise<PrismaUserPortugueseGoldenCoin[]> {
    return this.prisma.userPortugueseGoldenCoin.findMany(args);
  }
  async userPortugueseGoldenCoin(
    args: Prisma.UserPortugueseGoldenCoinFindUniqueArgs
  ): Promise<PrismaUserPortugueseGoldenCoin | null> {
    return this.prisma.userPortugueseGoldenCoin.findUnique(args);
  }
  async createUserPortugueseGoldenCoin(
    args: Prisma.UserPortugueseGoldenCoinCreateArgs
  ): Promise<PrismaUserPortugueseGoldenCoin> {
    return this.prisma.userPortugueseGoldenCoin.create(args);
  }
  async updateUserPortugueseGoldenCoin(
    args: Prisma.UserPortugueseGoldenCoinUpdateArgs
  ): Promise<PrismaUserPortugueseGoldenCoin> {
    return this.prisma.userPortugueseGoldenCoin.update(args);
  }
  async deleteUserPortugueseGoldenCoin(
    args: Prisma.UserPortugueseGoldenCoinDeleteArgs
  ): Promise<PrismaUserPortugueseGoldenCoin> {
    return this.prisma.userPortugueseGoldenCoin.delete(args);
  }
}
