/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserInvitationsService } from "../userInvitations.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserInvitationsCreateInput } from "./UserInvitationsCreateInput";
import { UserInvitations } from "./UserInvitations";
import { UserInvitationsFindManyArgs } from "./UserInvitationsFindManyArgs";
import { UserInvitationsWhereUniqueInput } from "./UserInvitationsWhereUniqueInput";
import { UserInvitationsUpdateInput } from "./UserInvitationsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserInvitationsControllerBase {
  constructor(
    protected readonly service: UserInvitationsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserInvitations })
  @nestAccessControl.UseRoles({
    resource: "UserInvitations",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserInvitationsCreateInput,
  })
  async createUserInvitations(
    @common.Body() data: UserInvitationsCreateInput
  ): Promise<UserInvitations> {
    return await this.service.createUserInvitations({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        invitationCode: true,
        status: true,
        invitationDate: true,
        expirationDate: true,
        invitedBy: true,
        invitedUser: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserInvitations] })
  @ApiNestedQuery(UserInvitationsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserInvitations",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userInvitationsItems(
    @common.Req() request: Request
  ): Promise<UserInvitations[]> {
    const args = plainToClass(UserInvitationsFindManyArgs, request.query);
    return this.service.userInvitationsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        invitationCode: true,
        status: true,
        invitationDate: true,
        expirationDate: true,
        invitedBy: true,
        invitedUser: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserInvitations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserInvitations",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userInvitations(
    @common.Param() params: UserInvitationsWhereUniqueInput
  ): Promise<UserInvitations | null> {
    const result = await this.service.userInvitations({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        invitationCode: true,
        status: true,
        invitationDate: true,
        expirationDate: true,
        invitedBy: true,
        invitedUser: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserInvitations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserInvitations",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserInvitationsUpdateInput,
  })
  async updateUserInvitations(
    @common.Param() params: UserInvitationsWhereUniqueInput,
    @common.Body() data: UserInvitationsUpdateInput
  ): Promise<UserInvitations | null> {
    try {
      return await this.service.updateUserInvitations({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          invitationCode: true,
          status: true,
          invitationDate: true,
          expirationDate: true,
          invitedBy: true,
          invitedUser: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserInvitations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserInvitations",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserInvitations(
    @common.Param() params: UserInvitationsWhereUniqueInput
  ): Promise<UserInvitations | null> {
    try {
      return await this.service.deleteUserInvitations({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          invitationCode: true,
          status: true,
          invitationDate: true,
          expirationDate: true,
          invitedBy: true,
          invitedUser: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
