/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GuildsMembersService } from "../guildsMembers.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GuildsMembersCreateInput } from "./GuildsMembersCreateInput";
import { GuildsMembers } from "./GuildsMembers";
import { GuildsMembersFindManyArgs } from "./GuildsMembersFindManyArgs";
import { GuildsMembersWhereUniqueInput } from "./GuildsMembersWhereUniqueInput";
import { GuildsMembersUpdateInput } from "./GuildsMembersUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GuildsMembersControllerBase {
  constructor(
    protected readonly service: GuildsMembersService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GuildsMembers })
  @nestAccessControl.UseRoles({
    resource: "GuildsMembers",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: GuildsMembersCreateInput,
  })
  async createGuildsMembers(
    @common.Body() data: GuildsMembersCreateInput
  ): Promise<GuildsMembers> {
    return await this.service.createGuildsMembers({
      data: {
        ...data,

        guild: data.guild
          ? {
              connect: data.guild,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        joinedAt: true,
        role: true,

        guild: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [GuildsMembers] })
  @ApiNestedQuery(GuildsMembersFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GuildsMembers",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async guildsMembersItems(
    @common.Req() request: Request
  ): Promise<GuildsMembers[]> {
    const args = plainToClass(GuildsMembersFindManyArgs, request.query);
    return this.service.guildsMembersItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        joinedAt: true,
        role: true,

        guild: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GuildsMembers })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GuildsMembers",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async guildsMembers(
    @common.Param() params: GuildsMembersWhereUniqueInput
  ): Promise<GuildsMembers | null> {
    const result = await this.service.guildsMembers({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        joinedAt: true,
        role: true,

        guild: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GuildsMembers })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GuildsMembers",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: GuildsMembersUpdateInput,
  })
  async updateGuildsMembers(
    @common.Param() params: GuildsMembersWhereUniqueInput,
    @common.Body() data: GuildsMembersUpdateInput
  ): Promise<GuildsMembers | null> {
    try {
      return await this.service.updateGuildsMembers({
        where: params,
        data: {
          ...data,

          guild: data.guild
            ? {
                connect: data.guild,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          joinedAt: true,
          role: true,

          guild: {
            select: {
              id: true,
            },
          },

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GuildsMembers })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GuildsMembers",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGuildsMembers(
    @common.Param() params: GuildsMembersWhereUniqueInput
  ): Promise<GuildsMembers | null> {
    try {
      return await this.service.deleteGuildsMembers({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          joinedAt: true,
          role: true,

          guild: {
            select: {
              id: true,
            },
          },

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
