/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  GuildsMembers as PrismaGuildsMembers,
  Guild as PrismaGuild,
  User as PrismaUser,
} from "@prisma/client";

export class GuildsMembersServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.GuildsMembersCountArgs, "select">
  ): Promise<number> {
    return this.prisma.guildsMembers.count(args);
  }

  async guildsMembersItems(
    args: Prisma.GuildsMembersFindManyArgs
  ): Promise<PrismaGuildsMembers[]> {
    return this.prisma.guildsMembers.findMany(args);
  }
  async guildsMembers(
    args: Prisma.GuildsMembersFindUniqueArgs
  ): Promise<PrismaGuildsMembers | null> {
    return this.prisma.guildsMembers.findUnique(args);
  }
  async createGuildsMembers(
    args: Prisma.GuildsMembersCreateArgs
  ): Promise<PrismaGuildsMembers> {
    return this.prisma.guildsMembers.create(args);
  }
  async updateGuildsMembers(
    args: Prisma.GuildsMembersUpdateArgs
  ): Promise<PrismaGuildsMembers> {
    return this.prisma.guildsMembers.update(args);
  }
  async deleteGuildsMembers(
    args: Prisma.GuildsMembersDeleteArgs
  ): Promise<PrismaGuildsMembers> {
    return this.prisma.guildsMembers.delete(args);
  }

  async getGuild(parentId: string): Promise<PrismaGuild | null> {
    return this.prisma.guildsMembers
      .findUnique({
        where: { id: parentId },
      })
      .guild();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.guildsMembers
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
