/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GuildsCoinsService } from "../guildsCoins.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GuildsCoinsCreateInput } from "./GuildsCoinsCreateInput";
import { GuildsCoins } from "./GuildsCoins";
import { GuildsCoinsFindManyArgs } from "./GuildsCoinsFindManyArgs";
import { GuildsCoinsWhereUniqueInput } from "./GuildsCoinsWhereUniqueInput";
import { GuildsCoinsUpdateInput } from "./GuildsCoinsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GuildsCoinsControllerBase {
  constructor(
    protected readonly service: GuildsCoinsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GuildsCoins })
  @nestAccessControl.UseRoles({
    resource: "GuildsCoins",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: GuildsCoinsCreateInput,
  })
  async createGuildsCoins(
    @common.Body() data: GuildsCoinsCreateInput
  ): Promise<GuildsCoins> {
    return await this.service.createGuildsCoins({
      data: {
        ...data,

        guild: data.guild
          ? {
              connect: data.guild,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        coins: true,

        guild: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [GuildsCoins] })
  @ApiNestedQuery(GuildsCoinsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GuildsCoins",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async guildsCoinsItems(
    @common.Req() request: Request
  ): Promise<GuildsCoins[]> {
    const args = plainToClass(GuildsCoinsFindManyArgs, request.query);
    return this.service.guildsCoinsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        coins: true,

        guild: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GuildsCoins })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GuildsCoins",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async guildsCoins(
    @common.Param() params: GuildsCoinsWhereUniqueInput
  ): Promise<GuildsCoins | null> {
    const result = await this.service.guildsCoins({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        coins: true,

        guild: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GuildsCoins })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GuildsCoins",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: GuildsCoinsUpdateInput,
  })
  async updateGuildsCoins(
    @common.Param() params: GuildsCoinsWhereUniqueInput,
    @common.Body() data: GuildsCoinsUpdateInput
  ): Promise<GuildsCoins | null> {
    try {
      return await this.service.updateGuildsCoins({
        where: params,
        data: {
          ...data,

          guild: data.guild
            ? {
                connect: data.guild,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          coins: true,

          guild: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GuildsCoins })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GuildsCoins",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGuildsCoins(
    @common.Param() params: GuildsCoinsWhereUniqueInput
  ): Promise<GuildsCoins | null> {
    try {
      return await this.service.deleteGuildsCoins({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          coins: true,

          guild: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
