/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  GuildsJoinInvitations as PrismaGuildsJoinInvitations,
  Guild as PrismaGuild,
} from "@prisma/client";

export class GuildsJoinInvitationsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.GuildsJoinInvitationsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.guildsJoinInvitations.count(args);
  }

  async guildsJoinInvitationsItems(
    args: Prisma.GuildsJoinInvitationsFindManyArgs
  ): Promise<PrismaGuildsJoinInvitations[]> {
    return this.prisma.guildsJoinInvitations.findMany(args);
  }
  async guildsJoinInvitations(
    args: Prisma.GuildsJoinInvitationsFindUniqueArgs
  ): Promise<PrismaGuildsJoinInvitations | null> {
    return this.prisma.guildsJoinInvitations.findUnique(args);
  }
  async createGuildsJoinInvitations(
    args: Prisma.GuildsJoinInvitationsCreateArgs
  ): Promise<PrismaGuildsJoinInvitations> {
    return this.prisma.guildsJoinInvitations.create(args);
  }
  async updateGuildsJoinInvitations(
    args: Prisma.GuildsJoinInvitationsUpdateArgs
  ): Promise<PrismaGuildsJoinInvitations> {
    return this.prisma.guildsJoinInvitations.update(args);
  }
  async deleteGuildsJoinInvitations(
    args: Prisma.GuildsJoinInvitationsDeleteArgs
  ): Promise<PrismaGuildsJoinInvitations> {
    return this.prisma.guildsJoinInvitations.delete(args);
  }

  async getGuild(parentId: string): Promise<PrismaGuild | null> {
    return this.prisma.guildsJoinInvitations
      .findUnique({
        where: { id: parentId },
      })
      .guild();
  }
}
